// export const ACTION = 'ACTION';

// auth
export const NO_TOKEN = 'NO_TOKEN';
export const LOAD_TOKEN = 'LOAD_TOKEN';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';

// Users
export const GET_USERS = 'GET_USERS';
export const GETTING_USER = 'GETTING_USER';
export const GET_USER = 'GET_USER';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const DELETE_USER = 'DELETE_USER';

// Companies
export const GET_COMPANIES = 'GET_COMPANIES';
export const GETTING_COMPANY = 'GETTING_COMPANY';
export const GET_COMPANY = 'GET_COMPANY';
export const ADDING_COMPANY = 'ADDING_COMPANY';
export const ADD_COMPANY = 'ADD_COMPANY';
export const EDITING_COMPANY = 'EDITING_COMPANY';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const DELETING_COMPANY = 'DELETING_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const COMPANY_ERROR = 'COMPANY_ERROR';

// App
export const GET_COMPANIES_PUBLIC = 'GET_COMPANIES_PUBLIC';
export const UPDATE_SCREEN_ORIENTATION = 'UPDATE_SCREEN_ORIENTATION';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
