// auth
export const NO_TOKEN = 'NO_TOKEN';
export const TOKEN_LOADED = 'TOKEN_LOADED';
export const TOKEN_INVALID = 'TOKEN_INVALID';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// customer
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAIL = 'CUSTOMER_LOGIN_FAIL';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';

// App
export const UPDATE_SCREEN_ORIENTATION = 'UPDATE_SCREEN_ORIENTATION';
export const SET_SNACKBAR = 'SET_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
